use_default_settings: true

general:
  instance_name: ChatOne Search

search:
  safe_search: 1
  autocomplete: ''
  formats:
    - html
    - json

server:
  limiter: false
  image_proxy: false

ui:
  static_use_hash: true
